#!/usr/bin/env python3
"""Check and index the blog knowledge base (kb/). See kb/README.md.

  python3 tools/kb.py check      validate notes, report gaps, rewrite kb/index.md
  python3 tools/kb.py show NAME  print a note and the notes that link to it
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

KB = Path(__file__).resolve().parent.parent / "kb"
TYPES = {"projects": "project", "topics": "topic", "findings": "finding",
         "sources": "source", "media": "media", "posts": "post"}
STATUSES = {"unverified", "verified", "contradicted", "superseded"}
LINK = re.compile(r"\[\[([a-z0-9][a-z0-9-]*)\]\]")


def load():
    notes = {}
    errors = []
    for folder, kind in TYPES.items():
        for f in sorted((KB / folder).glob("*.md")):
            text = f.read_text()
            m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
            if not m:
                errors.append(f"{f.relative_to(KB)}: no frontmatter")
                continue
            meta = {}
            for line in m.group(1).splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip()] = re.sub(r"\s+#.*$", "", v.strip())
            name = meta.get("name", "")
            if name != f.stem:
                errors.append(f"{f.relative_to(KB)}: name '{name}' should match the file name '{f.stem}'")
            if meta.get("type") != kind:
                errors.append(f"{f.relative_to(KB)}: type '{meta.get('type')}' should be '{kind}' in {folder}/")
            if kind == "finding" and meta.get("status") not in STATUSES:
                errors.append(f"{f.relative_to(KB)}: status must be one of {', '.join(sorted(STATUSES))}")
            if kind == "finding" and meta.get("status") == "verified" and not LINK.search(meta.get("sources", "")):
                errors.append(f"{f.relative_to(KB)}: verified finding with no [[source]] in sources")
            if f.stem in notes:
                errors.append(f"{f.relative_to(KB)}: duplicate name, also {notes[f.stem]['path'].relative_to(KB)}")
            title = next((l[2:].strip() for l in m.group(2).splitlines() if l.startswith("# ")), f.stem)
            notes[f.stem] = {"path": f, "type": kind, "meta": meta, "title": title,
                             "links": set(LINK.findall(text)) - {f.stem}}
    return notes, errors


def backlinks(notes):
    back = defaultdict(set)
    for n, note in notes.items():
        for l in note["links"]:
            back[l].add(n)
    return back


def check():
    notes, errors = load()
    back = backlinks(notes)
    gaps = sorted({l for note in notes.values() for l in note["links"] if l not in notes})
    orphans = sorted(n for n, note in notes.items() if not back[n] and note["type"] not in ("post", "project"))
    lines = ["# Knowledge base index", "", "Generated by `tools/kb.py check`. Don't edit by hand.", ""]
    for folder, kind in TYPES.items():
        group = sorted((n for n in notes if notes[n]["type"] == kind), key=lambda n: notes[n]["title"].lower())
        if not group:
            continue
        lines.append(f"## {folder.capitalize()} ({len(group)})")
        lines.append("")
        for n in group:
            st = notes[n]["meta"].get("status")
            lines.append(f"- [[{n}]] {notes[n]['title']}" + (f" _({st})_" if st and kind == "finding" else ""))
        lines.append("")
    if gaps:
        lines += ["## Gaps: linked but not written", ""] + [f"- [[{g}]] (from {', '.join(sorted(back[g]))})" for g in gaps] + [""]
    (KB / "index.md").write_text("\n".join(lines))
    counts = defaultdict(int)
    for note in notes.values():
        counts[note["type"]] += 1
    print(f"{len(notes)} notes: " + ", ".join(f"{v} {k}" for k, v in sorted(counts.items())))
    unverified = sorted(n for n, note in notes.items() if note["meta"].get("status") == "unverified")
    if unverified:
        print(f"unverified findings ({len(unverified)}): {', '.join(unverified)}")
    if gaps:
        print(f"gaps ({len(gaps)}): {', '.join(gaps)}")
    if orphans:
        print(f"orphans, nothing links here ({len(orphans)}): {', '.join(orphans)}")
    if errors:
        print("errors:\n  " + "\n  ".join(errors))
        sys.exit(1)


def show(name):
    notes, _ = load()
    if name not in notes:
        sys.exit(f"no note {name}")
    print(notes[name]["path"].read_text())
    print("--- linked from:", ", ".join(sorted(backlinks(notes)[name])) or "nothing")


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "check":
        check()
    elif len(sys.argv) == 3 and sys.argv[1] == "show":
        show(sys.argv[2])
    else:
        sys.exit(__doc__)
